"""Génère un profil Vibe dédié à partir du runtime commun et de .mcp.json.

Aucun skill, manifeste existant, secret ou profil utilisateur n'est modifié.
Python 3.11+ ; Vibe 2.26.0 est la version contrôlée par le smoke optionnel.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
MCP_ALIAS = "ct_vibe_droit_francais"
MCP_TOOLS = ("search", "fetch", "search_articles", "get_article", "search_case_law", "get_decision")


def skill_names(root: Path) -> list[str]:
    names = sorted(json.loads((root / "upstream.json").read_text(encoding="utf-8"))["skills"])
    for name in names:
        if not (root / "skills" / name / "SKILL.md").is_file():
            raise ValueError(f"Skill absent : {name}")
    return names


def oauth_server(root: Path, *, client_id: str | None = None, port: int | None = None) -> dict:
    servers = json.loads((root / ".mcp.json").read_text(encoding="utf-8"))["mcpServers"]
    if set(servers) != {"droit-francais"}:
        raise ValueError("Un seul serveur droit-francais est attendu")
    source = servers["droit-francais"]
    if set(source) != {"type", "url", "oauth"} or set(source["oauth"]) != {"clientId", "callbackPort"}:
        raise ValueError("Configuration MCP inconnue : revoir sa traduction, sans ignorer de champ")
    url = urlsplit(source["url"])
    if source["type"] != "http" or url.scheme != "https" or not url.hostname or url.username or url.password or url.query or url.fragment:
        raise ValueError("Une URL MCP HTTPS sans identifiants ni paramètres est attendue")
    public_client = client_id if client_id is not None else source["oauth"]["clientId"]
    callback_port = port if port is not None else source["oauth"]["callbackPort"]
    if not isinstance(public_client, str) or not public_client.strip():
        raise ValueError("Un identifiant de client public est nécessaire")
    if type(callback_port) is not int or not 1024 <= callback_port <= 65535:
        raise ValueError("Port callback invalide")
    return {
        "name": MCP_ALIAS, "transport": "http", "url": source["url"],
        "sampling_enabled": False,
        "auth": {"type": "oauth", "scopes": [], "client_id": public_client, "redirect_port": callback_port},
    }


def config_text(root: Path, *, mcp: bool = True, client_id: str | None = None,
                port: int | None = None, model: str | None = None) -> str:
    root = root.resolve()
    quote = lambda x: json.dumps(x, ensure_ascii=False)
    names = skill_names(root)
    tools = ["skill", "read_file"] + ([f"{MCP_ALIAS}_{name}" for name in MCP_TOOLS] if mcp else [])
    # web_fetch remains ASK: the campaign runtime approves only the case's official origins.
    tools.append("web_fetch")
    lines = [
        "# Generated by scripts/configure_vibe.py; source files remain authoritative.",
        f"skill_paths = [{quote(str(root / 'skills'))}]",
        f"enabled_skills = {quote(names)}",
        f"enabled_tools = {quote(tools)}",
        "experimental_enable_registry_skills = false",
        'default_agent = "accept-edits"',
        "enable_telemetry = false", "enable_update_checks = false",
        "include_project_context = false", "api_timeout = 60.0",
        "api_retry_max_elapsed_time = 20.0",
    ]
    if model is not None:
        lines.append(f"active_model = {quote(model)}")
    lines += [
        "", "[session_logging]", "enabled = false", "generate_titles = false",
        "", "[tools.skill]", 'permission = "always"',
        "", "[tools.read_file]", 'permission = "ask"',
        "", "[tools.web_fetch]", 'permission = "ask"',
    ]
    if mcp:
        server = oauth_server(root, client_id=client_id, port=port)
        lines += ["", "[[mcp_servers]]", f"name = {quote(server['name'])}",
                  f"transport = {quote(server['transport'])}", f"url = {quote(server['url'])}",
                  "sampling_enabled = false", "", "[mcp_servers.auth]"]
        for key, value in server["auth"].items():
            lines.append(f"{key} = {quote(value)}")
        for name in MCP_TOOLS:
            lines += ["", f"[tools.{quote(MCP_ALIAS + '_' + name)}]", 'permission = "always"']
    else:
        # An explicit empty array prevents accidental nominal mode in this standalone profile.
        lines.insert(1, "mcp_servers = []")
    return "\n".join(lines) + "\n"


def write_profile(home: Path, text: str) -> Path:
    """Create once; identical regeneration is safe, any existing drift is rejected."""
    home = home.expanduser().resolve()
    home.mkdir(parents=True, exist_ok=True)
    path = home / "config.toml"
    if path.is_symlink():
        raise ValueError("Un profil ne peut pas être un lien symbolique")
    if path.exists():
        if path.read_text(encoding="utf-8") != text:
            raise ValueError("Profil existant différent : choisir un nouveau dossier, sans écrasement")
        return path
    if any(home.iterdir()):
        raise ValueError("Le nouveau profil doit être créé dans un dossier vide")
    with path.open("x", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--home", type=Path, required=True, help="Nouveau profil dédié, pas ~/.vibe")
    parser.add_argument("--without-mcp", action="store_true")
    parser.add_argument("--client-id", help="Client public préenregistré pour Vibe, sans secret")
    parser.add_argument("--callback-port", type=int)
    args = parser.parse_args()
    try:
        text = config_text(ROOT, mcp=not args.without_mcp, client_id=args.client_id, port=args.callback_port)
        path = write_profile(args.home, text)
    except (ValueError, OSError) as error:
        parser.error(str(error))
    print(path)
    if not args.without_mcp:
        port = oauth_server(ROOT, client_id=args.client_id, port=args.callback_port)["auth"]["redirect_port"]
        print(f"Callback Vibe à autoriser côté OAuth : http://127.0.0.1:{port}/callback")
        print("Configuration traduite ; authentification et accès API restent à vérifier.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
